# Generated by Django 6.0.7 on 2026-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, help_text='Número de identificación del vehículo (17 caracteres).', max_length=17, unique=True, verbose_name='VIN')),
                ('make', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('trim', models.CharField(blank=True, max_length=100, verbose_name='Versión')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio estimado')),
                ('currency', models.CharField(blank=True, default='USD', max_length=8, verbose_name='Moneda')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='URL de origen')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Payload completo extraído del sitio, por si hace falta después.', verbose_name='Datos crudos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
