# Generated by Django 6.0.7 on 2026-07-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador')),
                ('base_url', models.URLField(max_length=500, verbose_name='URL base')),
                ('vin_path_template', models.CharField(default='/inventory/vin/{vin}', help_text='Ruta que se agrega a la URL base para consultar un VIN. Usa {vin} como marcador. Ej: /inventory/vin/{vin}', max_length=300, verbose_name='Plantilla de ruta por VIN')),
                ('provider_key', models.CharField(default='generic', help_text="Clave del provider a usar. 'generic' usa los selectores CSS de abajo. Otros valores requieren una clase registrada en el código.", max_length=50, verbose_name='Proveedor (código)')),
                ('selectors', models.JSONField(blank=True, default=dict, help_text='Mapa campo -> selector CSS. Campos: make, model, year, trim, mileage, estimated_price, currency, not_found. Ej: {"estimated_price": ".price-display"}', verbose_name='Selectores CSS')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Menor número = se intenta primero.', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('timeout', models.PositiveIntegerField(blank=True, help_text='Timeout específico para esta fuente. Si se deja vacío, usa el global.', null=True, verbose_name='Timeout (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Fuente de scraping',
                'verbose_name_plural': 'Fuentes de scraping',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='scraper.scrapersource', verbose_name='Fuente'),
        ),
    ]
