# Generated by Django 6.0.7 on 2026-07-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapersource_vehicle_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapersource',
            name='model_path_template',
            field=models.CharField(blank=True, default='', help_text='Ruta para consultar por MODELO (el scraping en segundo plano usa esta). Marcadores: {make} {model} {year} {trim}. Ej: /{make}/{model}/{year}/', max_length=300, verbose_name='Plantilla de ruta por modelo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_class',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Carrocería'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Decodificación NHTSA y payload del scraping, por si hace falta después.', verbose_name='Datos crudos'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, max_length=120, verbose_name='Versión'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('trim', models.CharField(blank=True, default='', max_length=120, verbose_name='Versión')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio estimado')),
                ('currency', models.CharField(blank=True, default='USD', max_length=8, verbose_name='Moneda')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='URL de origen')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Datos crudos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_models', to='scraper.scrapersource', verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Datos de modelo',
                'verbose_name_plural': 'Datos de modelos',
                'ordering': ['make', 'model', 'year', 'trim'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('trim', models.CharField(blank=True, default='', max_length=120, verbose_name='Versión')),
                ('vin', models.CharField(blank=True, db_index=True, default='', max_length=17, verbose_name='VIN origen')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En proceso'), ('done', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=10, verbose_name='Estado')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Último error')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scraper.vehiclemodel', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Trabajo de scraping',
                'verbose_name_plural': 'Trabajos de scraping',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='scraper.vehiclemodel', verbose_name='Datos de modelo'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'model', 'year', 'trim'), name='uniq_vehiclemodel_make_model_year_trim'),
        ),
        migrations.AddIndex(
            model_name='scrapejob',
            index=models.Index(fields=['status', 'created_at'], name='scraper_scr_status_f3978d_idx'),
        ),
    ]
