# Generated by Django 6.0.7 on 2026-07-21 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapersource_model_path_template_vehicle_body_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapejob',
            options={'ordering': ['created_at'], 'verbose_name': 'Scrape job', 'verbose_name_plural': 'Scrape jobs'},
        ),
        migrations.AlterModelOptions(
            name='scrapersource',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Scraper source', 'verbose_name_plural': 'Scraper sources'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['make', 'model', 'year', 'trim'], 'verbose_name': 'Model data', 'verbose_name_plural': 'Model data'},
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Attempts'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Last error'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scraper.vehiclemodel', verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Trim'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='vin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=17, verbose_name='Origin VIN'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='base_url',
            field=models.URLField(max_length=500, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='model_path_template',
            field=models.CharField(blank=True, default='', help_text='Path to query by MODEL (used by the background scraping). Placeholders: {make} {model} {year} {trim}. e.g. /{make}/{model}/{year}/', max_length=300, verbose_name='Model path template'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower number = tried first.', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='provider_key',
            field=models.CharField(default='generic', help_text="Provider class key. 'generic' uses the CSS selectors below; other values require a class registered in code.", max_length=50, verbose_name='Provider key'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='selectors',
            field=models.JSONField(blank=True, default=dict, help_text='Map of field -> CSS selector. Fields: make, model, year, trim, mileage, estimated_price, currency, not_found, model_price_nodes, wait_for.', verbose_name='CSS selectors'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, help_text='Source-specific timeout. If empty, the global one is used.', null=True, verbose_name='Timeout (s)'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='vin_path_template',
            field=models.CharField(default='/inventory/vin/{vin}', help_text='Path appended to the base URL to query a VIN. Use {vin} as placeholder.', max_length=300, verbose_name='VIN path template'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_class',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Body class'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated price'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='NHTSA decode and scraping payload, in case it is needed later.', verbose_name='Raw data'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='scraper.scrapersource', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, max_length=120, verbose_name='Trim'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='scraper.vehiclemodel', verbose_name='Model data'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(db_index=True, help_text='Vehicle Identification Number (17 characters).', max_length=17, unique=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated price'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw data'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_models', to='scraper.scrapersource', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Trim'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
