# Generated by Django 6.0.7 on 2026-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_scrapejob_options_alter_scrapersource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='price_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (high)'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='price_kind',
            field=models.CharField(blank=True, default='', help_text='How estimated_price was obtained: edmunds_suggested, msrp_range_mid, used_listings_median.', max_length=32, verbose_name='Price kind'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='price_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (low)'),
        ),
    ]
