# Generated by Django 6.0.7 on 2026-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_vehiclemodel_price_high_vehiclemodel_price_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapejob',
            options={'ordering': ['priority', 'created_at'], 'verbose_name': 'Scrape job', 'verbose_name_plural': 'Scrape jobs'},
        ),
        migrations.RemoveIndex(
            model_name='scrapejob',
            name='scraper_scr_status_f3978d_idx',
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='origin',
            field=models.CharField(blank=True, default='lookup', help_text='Who created the job: lookup, model_lookup, prewarm, crawl, refresh.', max_length=20, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100, verbose_name='Priority'),
        ),
        migrations.AddIndex(
            model_name='scrapejob',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='scraper_scr_status_bfb094_idx'),
        ),
    ]
