# Generated by Django 6.0.7 on 2026-07-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_scrapejob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='series',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Series'),
        ),
    ]
