# Generated by Django 6.0.7 on 2026-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_scrapejob_series'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scrapejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('make', 'model', 'year', 'trim'), name='uniq_active_scrapejob'),
        ),
    ]
