# Generated by Django 6.0.7 on 2026-07-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_scrapejob_uniq_active_scrapejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, default='', max_length=17, verbose_name='VIN')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Webhook')),
                ('notified', models.BooleanField(default=False, verbose_name='Notified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='scraper.scrapejob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Scrape subscriber',
                'verbose_name_plural': 'Scrape subscribers',
                'constraints': [models.UniqueConstraint(fields=('job', 'vin', 'webhook_url'), name='uniq_job_subscriber')],
            },
        ),
    ]
