# Generated by Django 6.0.7 on 2026-07-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_scrapesubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapejob',
            options={'ordering': ['priority', 'created_at'], 'verbose_name': 'Trabajo de scraping', 'verbose_name_plural': 'Trabajos de scraping'},
        ),
        migrations.AlterModelOptions(
            name='scrapersource',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Fuente de scraping', 'verbose_name_plural': 'Fuentes de scraping'},
        ),
        migrations.AlterModelOptions(
            name='scrapesubscriber',
            options={'verbose_name': 'Suscriptor', 'verbose_name_plural': 'Suscriptores'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['make', 'model', 'year', 'trim'], 'verbose_name': 'Datos de modelo', 'verbose_name_plural': 'Datos de modelos'},
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminado'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Último error'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='origin',
            field=models.CharField(blank=True, default='lookup', help_text='Who created the job: lookup, model_lookup, prewarm, crawl, refresh, rescrape.', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scraper.vehiclemodel', verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='series',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iniciado'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En curso'), ('done', 'Listo'), ('failed', 'Falló')], db_index=True, default='pending', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='vin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=17, verbose_name='VIN de origen'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='base_url',
            field=models.URLField(max_length=500, verbose_name='URL base'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='model_path_template',
            field=models.CharField(blank=True, default='', help_text='Path to query by MODEL (used by the background scraping). Placeholders: {make} {model} {year} {trim}. e.g. /{make}/{model}/{year}/', max_length=300, verbose_name='Plantilla de ruta de modelo'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower number = tried first.', verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='provider_key',
            field=models.CharField(default='generic', help_text="Provider class key. 'generic' uses the CSS selectors below; other values require a class registered in code.", max_length=50, verbose_name='Clave de proveedor'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='selectors',
            field=models.JSONField(blank=True, default=dict, help_text='Map of field -> CSS selector. Fields: make, model, year, trim, mileage, estimated_price, currency, not_found, model_price_nodes, wait_for.', verbose_name='Selectores CSS'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, help_text='Source-specific timeout. If empty, the global one is used.', null=True, verbose_name='Tiempo límite (s)'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='vin_path_template',
            field=models.CharField(default='/inventory/vin/{vin}', help_text='Path appended to the base URL to query a VIN. Use {vin} as placeholder.', max_length=300, verbose_name='Plantilla de ruta VIN'),
        ),
        migrations.AlterField(
            model_name='scrapesubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='scrapesubscriber',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='scraper.scrapejob', verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='scrapesubscriber',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Notificado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_class',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Carrocería'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio estimado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='NHTSA decode and scraping payload, in case it is needed later.', verbose_name='Datos crudos'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='scraper.scrapersource', verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de la fuente'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, max_length=120, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='scraper.vehiclemodel', verbose_name='Datos de modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio estimado'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='price_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio (máx)'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='price_kind',
            field=models.CharField(blank=True, default='', help_text='How estimated_price was obtained: edmunds_suggested, msrp_range_mid, used_listings_median.', max_length=32, verbose_name='Tipo de precio'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='price_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio (mín)'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos crudos'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_models', to='scraper.scrapersource', verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de la fuente'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
