# Generated by Django 6.0.7 on 2026-07-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_alter_scrapejob_options_alter_scrapersource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='scrape_failures',
            field=models.PositiveIntegerField(default=0, verbose_name='Fallos de scraping'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='model_path_template',
            field=models.CharField(blank=True, default='', help_text="Path to query by MODEL (used by the background scraping). Placeholders: {make} {model} {year} {trim}. e.g. /{make}/{model}/{year}/. NOTE: model scraping requires a DEDICATED provider (edmunds/cargurus); the 'generic' provider only supports VIN scraping.", max_length=300, verbose_name='Plantilla de ruta de modelo'),
        ),
    ]
