# Generated by Django 6.0.7 on 2026-07-28 21:19
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


def dedupe_vehiclemodels(apps, schema_editor):
    """Fusiona filas duplicadas bajo la nueva clave (case-insensitive, year NULL==0)
    ANTES de crear el índice único; si no, el AddConstraint fallaría con los datos
    que el constraint anterior (case-sensitive) permitía.

    Data-driven e idempotente: NO hardcodea ids (en prod son otros). Por cada grupo
    conserva la fila más recientemente actualizada (coherente con services._find_model,
    que lee .order_by("-updated_at")), repunta a ella las FKs que apuntaban a los
    duplicados (ambas son on_delete=SET_NULL, así que un borrado directo las perdería)
    y luego borra los duplicados.
    """
    VehicleModel = apps.get_model("scraper", "VehicleModel")
    Vehicle = apps.get_model("scraper", "Vehicle")
    ScrapeJob = apps.get_model("scraper", "ScrapeJob")

    groups = {}
    for vm in VehicleModel.objects.all().order_by("-updated_at", "-id"):
        key = (
            (vm.make or "").lower(),
            (vm.model or "").lower(),
            (vm.trim or "").lower(),
            vm.year or 0,
        )
        groups.setdefault(key, []).append(vm)

    for rows in groups.values():
        if len(rows) < 2:
            continue
        keeper = rows[0]  # más reciente (order_by -updated_at, -id)
        loser_ids = [r.id for r in rows[1:]]
        # Repunta las FKs al keeper antes de borrar (no perder el vínculo).
        Vehicle.objects.filter(vehicle_model_id__in=loser_ids).update(vehicle_model=keeper)
        ScrapeJob.objects.filter(result_id__in=loser_ids).update(result=keeper)
        VehicleModel.objects.filter(id__in=loser_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_vehiclemodel_scrape_failures_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclemodel',
            name='uniq_vehiclemodel_make_model_year_trim',
        ),
        # Limpia duplicados preexistentes antes de imponer el índice único.
        migrations.RunPython(dedupe_vehiclemodels, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('make'), django.db.models.functions.text.Lower('model'), django.db.models.functions.text.Lower('trim'), django.db.models.functions.comparison.Coalesce('year', 0), name='uniq_vehiclemodel_ci'),
        ),
    ]
