# Generated by Django 6.0.7 on 2026-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_remove_vehiclemodel_uniq_vehiclemodel_make_model_year_trim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio (máx)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_kind',
            field=models.CharField(blank=True, default='', help_text='vinaudit_market, edmunds_market, cargurus_listings_median, ...', max_length=32, verbose_name='Tipo de precio'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio (mín)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vinaudit_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='VinAudit consultado (fecha)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vinaudit_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Precio VinAudit (fecha)'),
        ),
    ]
